import type {
  BlogCategory,
  BlogPostPreview,
  Project,
  Stat,
  TimelineItem,
} from './types'

export const BLOG_TOPICS: Record<BlogCategory, string[]> = {
  'Data Analytics': ['SQL', 'Power BI', 'Excel', 'Python'],
  'Data Engineering': ['ETL / ELT', 'Data Warehouse', 'Data Lake', 'Pipelines', 'Cloud'],
  'Data Science': ['Machine Learning'],
  Tecnologias: ['Databricks', 'dbt', 'Spark', 'Airflow', 'Azure'],
}

export const NAV_LINKS = [
  { label: 'Início', href: '#inicio' },
  { label: 'Sobre', href: '#sobre' },
  { label: 'Projetos', href: '#projetos' },
  { label: 'Experiência', href: '#experiencia' },
  { label: 'Contato', href: '#contato' },
]

export const PROJECTS: Project[] = [
  {
    title: 'StreamLit - Aplicação de Visualização de Dados',
    description: 'Aplicação analítica desenvolvida em Streamlit para apoiar a visualização e a predição de risco de defasagem escolar com base em indicadores educacionais e socioemocionais.',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80',
    technologies: ['Python', 'Streamlit', 'Pandas', 'Scikit-learn', 'Data Visualization', 'Machine Learning', 'Plotly', 'Joblib', 'Matplotlib'],
    status: 'Concluído',
    category: 'Python',
    githubUrl: 'https://github.com/KauanAltino/Datathon-Passos-Magicos-StreamLit/tree/StreamLit',
  },
  {
    title: 'DevOps Python FIAP',
    description: 'Projeto de implantação containerizada com Python e Docker. Aplicação Python simples que demonstra um processo de implantação bem-sucedido. O projeto utiliza Docker para containerização, facilitando a execução em diferentes ambientes.',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
    technologies: ['Python', 'Docker', 'DevOps'],
    status: 'Concluído',
    category: 'Python',
    githubUrl: 'https://github.com/KauanAltino/CP2_DEVOPS_PYTHON_FIAP',
  },
  {
    title: 'DayToday API',
    description: 'API REST desenvolvida para gerenciar rotinas e hábitos pessoais, permitindo o cadastro e acompanhamento de metas de forma organizada.',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
    technologies: ['Java', 'REST API', 'Spring Boot', 'Maven'],
    status: 'Concluído',
    category: 'Java',
    githubUrl: 'https://github.com/KauanAltino/DayToday',
  },
  {
    title: 'Programação Python',
    description: 'Projeto com exercícios práticos de programação em Python. ',
    image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80',
    technologies: ['Python', 'Algoritmos', 'Lógica de Programação', 'Estruturas de Dados'],
    status: 'Concluído',
    category: 'Data',
    githubUrl: 'https://github.com/KauanAltino/python_learning',
  },
  {
    title: 'DEVOPS FIAP',
    description: 'Projeto web Java de exemplo (Servlet + JSP) usado em exercícios/avaliações no curso da FIAP. O projeto foi adaptado para fins de estudo e prática de DevOps.',
    image: 'https://images.unsplash.com/photo-1438032005730-c779502df39b?auto=format&fit=crop&w=1200&q=80',
    technologies: ['Java', 'Servlet', 'JSP', 'Maven', 'Tomcat', 'Docker'],
    status: 'Concluído',
    category: 'Java',
    githubUrl: 'https://github.com/KauanAltino/CP2_DEVOPS_FIAP',
  },
  {
    title: 'Sistema de Alarme IOT',
    description: 'Projeto de um sistema de alarme IoT utilizando ESP32, MQTT, HiveMQ e Node-RED. O sistema permite detectar movimentos por meio de um sensor PIR, enviar os dados via MQTT e monitorar os eventos através de um dashboard no Node-RED, acionando um buzzer como alerta. O projeto também foi simulado utilizando o Wokwi para validar o funcionamento da comunicação entre os dispositivos.',
    image: 'https://images.unsplash.com/photo-1488229297570-58520851e868?auto=format&fit=crop&w=1200&q=80',
    technologies: ['ESP32', 'MQTT', 'HiveMQ', 'Node-RED', 'Wokwi'],
    status: 'Concluído',
    category: 'Automação',
    githubUrl: 'https://github.com/KauanAltino/Sistema_Alarmes_IOT',
  },
  {
    title: 'DevOps FIAP-CP3',
    description: 'Aplicação Spring Boot CRUD para gerenciamento de pedidos, produtos e usuários. Este projeto demonstra boas práticas de desenvolvimento em Java com arquitetura em camadas (Controller → Service → Repository → Database).',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80',
    technologies: ['Java', 'Spring Boot', 'Maven', 'SQL Server', 'MySQL', 'Docker', 'API REST', 'Junit'],
    status: 'Concluído',
    category: 'Java',
    githubUrl: 'https://github.com/KauanAltino/cp3_devops_2024',
  },
  {
    title: 'SustEnergy - Sistema de Gestão de Energia',
    description: 'O SustEnergy é uma aplicação Java baseada em Spring Boot criada para facilitar a gestão de dados de consumo de energia em comunidades, empresas e residências. O objetivo é promover o uso eficiente de recursos, monitorar fontes renováveis e auxiliar na tomada de decisões sustentáveis.',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80',
    technologies: ['Java', 'Spring Boot', 'H2 Database', 'Maven', 'API REST', 'Junit', 'Thymeleaf'],
    status: 'Concluído',
    category: 'Java',
    githubUrl: 'https://github.com/KauanAltino/SustEnergy',
  },
  {
    title: 'Sistema de Energia IOT',
    description: 'Sistema de monitoramento de energia integrado a dispositivos IoT. O sistema é composto por dois dispositivos: um sensor que coleta dados sobre consumo e geração de energia, e um atuador.',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80',
    technologies: ['ESP32', 'MQTT', 'HiveMQ', 'Node-RED', 'Wokwi'],
    status: 'Concluído',
    category: 'Automação',
    githubUrl: 'https://github.com/KauanAltino/Energia_IOT',
  },
  {
    title: 'Programa de DevOps',
    description: 'Este é um projeto Java simples demonstrando conceitos básicos de DevOps, incluindo construção com Maven, contêinerização e scripts de banco de dados.',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80',
    technologies: ['Java', 'Docker', 'Apache Maven', 'SQL Server', 'MySQL', 'Junit'],
    status: 'Concluído',
    category: 'Java',
    githubUrl: 'https://github.com/KauanAltino/programa_devops',
  },
  {
    title: 'DataScience - ALURA',
    description: 'Projeto desenvolvido durante o curso Data Science: Explorando e Analisando Dados, da Alura. O repositório reúne notebooks de análise exploratória de dados com foco em estatística descritiva, tratamento inicial de dados e visualização com Python.',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80',
    technologies: ['Python', 'Jupyter Notebook', 'Pandas', 'NumPy', 'Matplotlib', 'Seaborn'],
    status: 'Concluído',
    category: 'Python',
    githubUrl: 'https://github.com/KauanAltino/DataScience_ALURA',
  },
  {
    title: 'Data Visualization - ALURA',
    description: 'Projeto de estudo em Visualização de Dados com base nas aulas da Alura. O repositório contém notebooks com análises exploratórias, gráficos e insights obtidos a partir de conjuntos de dados diversos, utilizando bibliotecas como Matplotlib e Seaborn.',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80',
    technologies: ['Python', 'Jupyter Notebook', 'Pandas', 'NumPy', 'Matplotlib', 'Seaborn'],
    status: 'Em Andamento',
    category: 'Python',
    githubUrl: 'https://github.com/KauanAltino/DataVisualization_ALURA',
  },
  {
    title: 'Programa de Agendamento',
    description: 'Projeto de estudo em desenvolvimento de um programa de agendamento. O repositório contém scripts e documentação relacionados à implementação de funcionalidades de agendamento e gerenciamento de compromissos.',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80',
    technologies: ['Next.js 16', 'React 19', 'TypeScript', 'Tailwind CSS v4', 'Supabase (Database + Realtime)'],
    status: 'Concluído',
    category: 'Web',
    githubUrl: 'https://github.com/KauanAltino/Programa_agendamento',
  },
  {
    title: 'Meu portfólio pessoal',
    description: 'Projeto de estudo em desenvolvimento de um portfólio pessoal. O repositório contém scripts e documentação relacionados à implementação de funcionalidades do portfólio.',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80',
    technologies: ['typescript', 'JavaScript' ,'react', 'tailwindcss', 'vite', 'framer-motion', 'react-icons'],
    status: 'Em evolução',
    category: 'Web',
    githubUrl: 'https://github.com/KauanAltino/meu-portifolio',
  },
]

export const ABOUT_TIMELINE: TimelineItem[] = [
  {
    year: '2022',
    title: 'Início da Graduação em ADS (FIAP)',
    subtitle: 'Base em desenvolvimento e dados',
    description: 'Desenvolvimento de fundamentos em lógica, programação, bancos de dados e análise de sistemas.',
  },
  {
    year: '2022 - 2023',
    title: 'Bradesco Seguros - Estágio em Arquitetura de Sistemas',
    subtitle: 'Vivência corporativa em fluxos sistêmicos',
    description: 'Apoio na análise de processos, documentação técnica e interpretação de requisitos junto a times multidisciplinares.',
  },
  {
    year: '2024',
    title: 'Conclusão da Graduação em ADS',
    subtitle: 'Consolidação técnica',
    description: 'Conclusão do curso de Análise e Desenvolvimento de Sistemas com foco em evolução para a área de dados.',
  },
  {
    year: '2025 - 2026',
    title: 'Pós-graduação em Data Analytics (FIAP Pós-Tech)',
    subtitle: 'Especialização em análise de dados',
    description: 'Aprofundamento em Power BI, Python, Streamlit, Machine Learning, Spark, SQL e visualização de dados para tomada de decisão.',
  },
]

export const EXPERIENCE_TIMELINE: TimelineItem[] = [
  {
    year: 'Dez/2022 - Dez/2023',
    title: 'Estágio em Arquitetura de Sistemas | Bradesco Seguros',
    subtitle: 'São Paulo/SP',
    description: 'Atuação em análise de processos, organização de fluxos sistêmicos, documentação técnica e apoio à interpretação de requisitos.',
  },
  {
    year: '2024 - Atual',
    title: 'Projetos de Dados em Desenvolvimento',
    subtitle: 'Power BI, Python, SQL e Engenharia de Dados',
    description: 'Desenvolvimento de projetos envolvendo análise, tratamento, visualização e processamento de dados, com foco na construção de soluções práticas e evolução contínua em Data Analytics e Data Engineering.',
  },
  {
    year: 'Foco Atual',
    title: 'Data Analytics | Data Engineering',
    subtitle: 'Objetivo de carreira',
    description: 'Atuar na área de Dados, desenvolvendo análises, pipelines e soluções para transformar dados em informações confiáveis e apoiar decisões de negócio.',
  },
]

export const BLOG_PREVIEW: BlogPostPreview[] = [
  {
    title: 'Boas práticas para dashboards de KPIs no Power BI',
    excerpt: 'Como organizar métricas para facilitar leitura e tomada de decisão.',
    date: '15 Jun 2026',
    readTime: '6 min',
    category: 'Data Analytics',
    topic: 'Power BI',
  },
  {
    title: 'Análise exploratória de dados com Python e Pandas',
    excerpt: 'Um fluxo prático de limpeza, entendimento e geração de insights.',
    date: '03 Mai 2026',
    readTime: '8 min',
    category: 'Data Analytics',
    topic: 'Python',
    slug: 'analise-exploratoria-python-pandas',
  },
  {
    title: 'SQL para Data Analytics',
    excerpt: 'Um guia prático para consultar, transformar e analisar dados com PostgreSQL.',
    date: '14 Ago 2026',
    readTime: '25 min',
    category: 'Data Analytics',
    topic: 'SQL',
    slug: 'sql-data-analytics',
  },
  {
    title: 'Excel para Análise de Dados',
    excerpt: 'Como utilizar planilhas para organizar dados, criar métricas e apoiar decisões.',
    date: 'Em breve',
    readTime: 'Leitura em breve',
    category: 'Data Analytics',
    topic: 'Excel',
  },
  {
    title: 'ETL: organizando dados para análise',
    excerpt: 'Entenda o fluxo de extração, transformação e carregamento de dados.',
    date: 'Em breve',
    readTime: 'Leitura em breve',
    category: 'Data Engineering',
    topic: 'ETL / ELT',
  },
  {
    title: 'Data Warehouse: uma base para decisões',
    excerpt: 'Como dados integrados e históricos apoiam análises e indicadores de negócio.',
    date: 'Em breve',
    readTime: 'Leitura em breve',
    category: 'Data Engineering',
    topic: 'Data Warehouse',
  },
]

export const STATS: Stat[] = [
  { label: 'Projetos de Dados', value: 6, suffix: '+' },
  { label: 'Certificações', value: 6, suffix: '+' },
  { label: 'Formações FIAP', value: 2, suffix: '' },
  { label: 'Anos estudando', value: 4, suffix: '+' },
  { label: 'Ferramentas', value: 10, suffix: '+' },
]
